services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      - DATABASE_URL=file:/app/data/dev.db
      - NODE_ENV=development
    networks:
      - transcendence
    volumes:
      - prisma-data:/app/data

  frontend:
      build: ./frontend
      ports:
        - "8000:8000"
      networks:
        - transcendence
      depends_on:
        - backend

networks:
  transcendence:
    driver: bridge

volumes:
  prisma-data:
