services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      - DATABASE_URL=file:/app/data/dev.db
      - NODE_ENV=development
    networks:
      - transcendence
    volumes:
       - prisma-data:/app/data
       - ./backend/src:/app/src
       - ./backend/prisma:/app/prisma

  frontend:
      build: ./frontend
      ports:
        - "5173:5173"
      networks:
        - transcendence
      depends_on:
        - backend
      volumes:
        - ./frontend/src:/app/src
        - ./frontend/index.html:/app/index.html

networks:
  transcendence:
    driver: bridge

volumes:
  prisma-data:
