services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      - DATABASE_URL=file:/app/data/dev.db
      - NODE_ENV=development
    networks:
      - transcendence
    volumes:
      - prisma-data:/app/data
      - ./backend:/app
      - /app/node_modules

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - transcendence

networks:
  transcendence:
    driver: bridge

volumes:
  prisma-data:
