events {}

http {
	# Load standard MIME types so .js/.css are served with correct Content-Type
	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	upstream backend {
		server backend:3000;
	}

	server {
		listen 80;
		server_name localhost;
		return 301 https://$host$request_uri;
	}

	server {
		listen 443 ssl;
		server_name localhost;

		ssl_certificate /etc/nginx/ssl/selfsigned.crt;
		ssl_certificate_key /etc/nginx/ssl/selfsigned.key;

		root /usr/share/nginx/html;
		index index.html;

		location /ws {
			proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://backend;
		}

		location / {
			try_files $uri $uri/ /index.html;
		}

		location /api/ {
			try_files $uri $uri/ @api_proxy;
		}

		location @api_proxy {
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://backend;
        }

        # Upload files proxy
        location /uploads/ {
            proxy_pass http://backend/uploads/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
	}
}
