@baseUrl = http://localhost:3000/api/friends
@token = 1beb5f74-4b83-4679-a191-c587c96b20ad
@userId = 7068cc49-2ab8-45e8-805e-226f50678af7

### SENDS A FRIENDSHIP REQUEST
POST {{baseUrl}}/ HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"addresseeDisplayName": "KeoLima"
}
