@baseUrl = http://localhost:3000/api/friends
@token = d5b37df3-1251-4726-8118-eb1950f4e163
@userId = 99379f4c-3253-4581-94a0-603ec8fa4fec

### ACEPT REQUEST
PUT {{baseUrl}}/accept/c406e87a-f145-4fd7-a527-1822c383e686 HTTP/1.1
Authorization: Bearer {{token}}

### REJECT REQUEST
PUT {{baseUrl}}/reject/ca29aef9-cc32-496e-9e94-add05fbdc05d HTTP/1.1
Authorization: Bearer {{token}}

### DELETE REQUEST
DELETE {{baseUrl}}/c406e87a-f145-4fd7-a527-1822c383e686 HTTP/1.1
Authorization: Bearer {{token}}

### GET ACTIVE FRIENDSHIP
GET {{baseUrl}}/ HTTP/1.1
Authorization: Bearer {{token}}

### GET PENDING FRIENDSHIP
GET {{baseUrl}}/requests HTTP/1.1
Authorization: Bearer {{token}}

### GET FRIEND HISTORY
GET {{baseUrl}}/history/ HTTP/1.1
Authorization: Bearer {{token}}

### SENDS A FRIENDSHIP REQUEST
POST {{baseUrl}}/ HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"addresseeDisplayName": "KeoLima"
}
