### CREATE A GAME
POST http://localhost:3000/api/games HTTP/1.1
Content-Type: application/json
Authorization: Bearer d61aa2de-5cfd-4610-8ddf-67cea6f507af

{
   "createdBy": "keomalima@icloud.com",
   "type": "ONLINE"
}