@baseUrl = http://localhost:3000/api/games
@token = 6066414e-4823-437e-b6e1-225e283294fb
@userId = 4e20da12-b3f9-42ab-8670-803fceecb452

### CREATE A GAME
POST {{baseUrl}}/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "type": "ONLINE",
   "scoreToWin": 10
}