@baseUrl = http://localhost:3000/api/users
@token = eb792354-ccd3-45da-a8ce-dd6b82f7f8cf
@userId = 12c51269-a077-4657-bcef-d5dc0654ce31

### CREATE AN USER
POST {{baseUrl}} HTTP/1.1
Content-Type: application/json

{
   "email": "keomalima@icloud.com",
   "name": "Keoma",
   "surname": "Lima",
   "password": "123456",
   "displayName": "KeoLimaa",
   "city": "Lyon",
   "avatarUrl": null
}

### LOGIN AN USER
# @name login
POST {{baseUrl}}/login HTTP/1.1
Content-Type: application/json

{
   "email": "keomalima@icloud.com",
   "password": "123456"
}

### GET AN USER (requires authentication)
GET {{baseUrl}}/{{userId}} HTTP/1.1
Authorization: Bearer {{token}}

### LOGOUT AN USER 
POST {{baseUrl}}/logout HTTP/1.1
Authorization: Bearer {{token}}

### UPDATE AN USER
PUT {{baseUrl}}/me HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "email": "betsy@icloud.com",
   "name": "Betsy",
   "surname": "Lima",
   "displayName": "KeoLima",
   "password": "123456",
   "city": "Lyon",
   "avatarUrl": null
}

### UPLOAD AVATAR
POST {{baseUrl}}/upload HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatarUrl"; filename="ProfileCV.jpg"
Content-Type: image/jpeg

< /Users/keomalima/Documents/42/stage/ProfileCV.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### DELETES AN USER
DELETE {{baseUrl}}/users HTTP/1.1
Authorization: Bearer {{token}}