@baseUrl = http://localhost:3000/api/users
@userId = 073b578e-77ab-4d89-bc59-4b79a93ca78a
@token = 5b2de7be-0495-4b8d-8778-41513823716c

### GET ALL USERS
GET {{baseUrl}} HTTP/1.1

### DELETE BASE
DELETE {{baseUrl}}/clean HTTP/1.1

### CREATE AN USER (AS JSON)
POST {{baseUrl}}/ HTTP/1.1
Content-Type: application/json

{
	"my": "teste",
	"email": "betsy@icloud.com",
	"name": "Betsy",
	"surname": "Lima",
	"displayName": "Betsy",
	"password": "123456",
	"avatarUrl": null
}

### CREATE AN USER
POST {{baseUrl}} HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="email"

keomalima@icloud.com
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

Keoma
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="surname"

Lima
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="password"

1234
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="displayName"

KeoLima
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatarFile"; filename="ProfileCV.jpg"
Content-Type: image/jpeg

< /Users/keomalima/Downloads/keo.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### LOGIN AN USER
# @name login
POST {{baseUrl}}/login HTTP/1.1
Content-Type: application/json

{
   "email": "betsy@icloud.com",
   "password": "123456"
}

### GET AN USER (requires authentication)
GET {{baseUrl}}/{{userId}} HTTP/1.1
Authorization: Bearer {{token}}

### LOGOUT AN USER 
POST {{baseUrl}}/logout HTTP/1.1
Authorization: Bearer {{token}}

### UPDATE AN USER
PUT {{baseUrl}}/me HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "email": "betsy2@icloud.com",
   "name": "Betsyy",
   "surname": "Lima",
   "displayName": "KeoLima",
   "password": "123456",
   "avatarUrl": null
}

### UPLOAD AVATAR
POST {{baseUrl}}/upload HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatarFile"; filename="ProfileCV.jpg"
Content-Type: image/jpeg

< /Users/keomalima/Downloads/keo.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### GET USER PROFILE PICTURE
GET http://localhost:3000/uploads/avatars/335029f2-cdb8-4107-9413-d6018e30a829.jpg HTTP/1.1

### DELETES AN USER
DELETE {{baseUrl}} HTTP/1.1
Authorization: Bearer {{token}}